name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ajusta a la rama que deseas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no -r ./mi-app ubuntu@50.17.121.114 :/var/www/html/trabajo2

      - name: Restart Nginx
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ubuntu@50.17.121.114  'sudo systemctl restart nginx'
